name: Run Tests

# Run the workflow whenever there's a push or pull request to the main branch
on:
  push:
    branches: 
      - main
      - TEST_RESTAPI
  pull_request:
    branches: 
      - main
      - TEST_RESTAPI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Use Python version of your choice

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Flask

    - name: Run tests
      run: |
        python -m unittest discover -s . -p "TestDatabase.py"
